// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/tic-tac-toe": {
    params: {};
  };
  "/todo": {
    params: {};
  };
  "/product-table": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/tic-tac-toe" | "/todo" | "/product-table";
  };
  "./routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "./routes/tic-tac-toe.tsx": {
    id: "routes/tic-tac-toe";
    page: "/tic-tac-toe";
  };
  "./routes/todo.tsx": {
    id: "routes/todo";
    page: "/todo";
  };
  "./routes/product-table.tsx": {
    id: "routes/product-table";
    page: "/product-table";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.tsx");
  "routes/_index": typeof import("./src/./routes/_index.tsx");
  "routes/tic-tac-toe": typeof import("./src/./routes/tic-tac-toe.tsx");
  "routes/todo": typeof import("./src/./routes/todo.tsx");
  "routes/product-table": typeof import("./src/./routes/product-table.tsx");
};